name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy
    needs: build
    # if: github.ref == 'refs/heads/main'
    secrets: inherit
    uses: ./.github/workflows/deploy.yml