on:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: '.,!.github'
          target: ${{ secrets.DEPLOY_DIRECTORY }}
          rm: true # Remove target folder before upload data

      - name: SSH to server & Deploy app
        uses: appleboy/ssh-action@v1.0.0
        env:
          DEPLOY_DIRECTORY: ${{ secrets.DEPLOY_DIRECTORY }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: DEPLOY_DIRECTORY,ENV_FILE
          script: |
            echo "***DEPLOYER***: Change to deploy directory..."
            cd $DEPLOY_DIRECTORY

            echo '***DEPLOYER*** Override .env file'
            echo -e "$ENV_FILE" > .env

            echo '***DEPLOYER*** Install dependencies'
            npm install

            echo '***DEPLOYER*** Build code'
            npm run build

            echo '***DEPLOYER*** Apply migrations to database'
            npx prisma migrate deploy

            echo "***DEPLOYER*** Delete running app"
            npm run delete:prod

            echo '***DEPLOYER*** Running app'
            npm run start:prod
